/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoteResponse } from './noteResponse';


export interface GetNotes200Response { 
    data?: Array<NoteResponse>;
    success?: boolean;
    error?: object;
}

