/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NoteEntityResponse { 
    /**
     * Note entity id.
     */
    noteEntityId: string;
    /**
     * Entity id.
     */
    entityId: string;
    /**
     * Entity type id.
     */
    entityTypeId: NoteEntityResponse.EntityTypeIdEnum;
    /**
     * Entity code name.
     */
    entityTypeCodeName: NoteEntityResponse.EntityTypeCodeNameEnum;
    /**
     * Entity display name.
     */
    entityTypeDisplayName: string;
}
export namespace NoteEntityResponse {
    export type EntityTypeIdEnum = 1 | 2 | 3 | 4;
    export const EntityTypeIdEnum = {
        NUMBER_1: 1 as EntityTypeIdEnum,
        NUMBER_2: 2 as EntityTypeIdEnum,
        NUMBER_3: 3 as EntityTypeIdEnum,
        NUMBER_4: 4 as EntityTypeIdEnum
    };
    export type EntityTypeCodeNameEnum = 'contact' | 'company' | 'unit' | 'invoice';
    export const EntityTypeCodeNameEnum = {
        Contact: 'contact' as EntityTypeCodeNameEnum,
        Company: 'company' as EntityTypeCodeNameEnum,
        Unit: 'unit' as EntityTypeCodeNameEnum,
        Invoice: 'invoice' as EntityTypeCodeNameEnum
    };
}


