/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoteEntityResponse } from './noteEntityResponse';
import { TagResponse } from './tagResponse';


export interface NoteResponse { 
    /**
     * Note Id
     */
    noteId: string;
    /**
     * Note title
     */
    title: string;
    /**
     * Note text body
     */
    text: string;
    /**
     * Org Id
     */
    orgId: string;
    /**
     * Site Id
     */
    siteId: string;
    /**
     * Created by
     */
    createdBy: string;
    /**
     * Created at.
     */
    createdAt: string;
    /**
     * Full name of the creator of the note.
     */
    createdByFullName: string;
    /**
     * Org tags associated with this note.
     */
    tags: Array<TagResponse>;
    /**
     * Entities associated with this note.
     */
    entities: Array<NoteEntityResponse>;
}

