/**
 * ManageSpace Note API
 * ManageSpace Note API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TagResponse { 
    /**
     * Tag Id
     */
    tagId: string;
    /**
     * Tag text
     */
    text: string;
    /**
     * Organization Id
     */
    orgId: string;
    /**
     * Site Id
     */
    siteId: string;
}

